config/routes.rb
Rent::Application.routes.draw do

  scope '(:locale)' do
    root "houses#index"

    resources :ads
    devise_for :users
    resources :houses
    resources :profiles
    post 'lang_change', to: 'application#lang_change'
    get "/profile", to: 'profiles#show_profile'
    
  end

  

end

app/models/ad.rb
class Ad < ActiveRecord::Base
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ad }
      else
        format.html { render action: 'new' }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:title, :description, :price)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/views/ads/_form.html.slim
= form_for @ad do |f|
  - if @ad.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ad.errors.count, "error")} prohibited this ad from being saved:"
      ul
        - @ad.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :price
    = f.text_field :price
  .actions = f.submit 'Save'

app/views/ads/edit.html.slim
h1 Editing ad

== render 'form'

= link_to 'Show', @ad
'|
= link_to 'Back', ads_path

app/views/ads/index.html.slim
h1 Listing ads

table
  tr
    th Title
    th Description
    th Price
    th
    th
    th

  - @ads.each do |ad|
    tr
      td = ad.title
      td = ad.description
      td = ad.price
      td = link_to 'Show', ad
      td = link_to 'Edit', edit_ad_path(ad)
      td = link_to 'Destroy', ad, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Ad', new_ad_path

app/views/ads/new.html.slim
h1 New ad

== render 'form'

= link_to 'Back', ads_path

app/views/ads/show.html.slim
p#notice = notice

p
  strong Title:
  = @ad.title
p
  strong Description:
  = @ad.description
p
  strong Price:
  = @ad.price

= link_to 'Edit', edit_ad_path(@ad)
'|
= link_to 'Back', ads_path