config/routes.rb
Rent::Application.routes.draw do

  scope '(:locale)' do
    root "houses#index"

    resources :ads
    devise_for :users
    resources :houses
    resources :profiles
    post 'lang_change', to: 'application#lang_change'
    get "/profile", to: 'profiles#show_profile'
    
  end

  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates_uniqueness_of :company_name
  belongs_to :user

  before_save :company_name_transliterate, :to_param

  

  

  def to_param
    if url == "" || url == url.nil?
      id
    else
      url
    end
  end
  
  private

  def company_name_transliterate
    if !company_name.nil?
      self.url = company_name.to_slug.transliterate(:russian).normalize.to_s
    else
      self.url = ""
    end
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_profile, only: [:edit, :update, :destroy]
  

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find_by_url(params[:id])
    if @profile.nil?
      @profile = Profile.find(params[:id])
    end
    rescue
      render file: 'public/404', status: 404
  end

  def show_profile
    @profile = current_user.profile
    render 'show'
  rescue
    render file: 'public/404', status: 404
  end

  # GET /profiles/new
  # def new
    # @profile = Profile.new
  # end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = current_user.profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit( :email, :company_name, :phone_number, :user_id, :description, :url, :twitter, :website, :facebook, :owner_name)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.slim
.row
  .large-12.columns
    = form_for(@profile, data: {abide: ""}) do |f|
      - if @profile.errors.any?
        /#error_explanation
        .alert-box
          = pluralize(@profile.errors.count, "error") 
          |  prohibited this profile from being saved:
    
      fieldset.profile
        legend = t('.profile')
        .row
          .small-5.columns.large-3
            = f.label :company_name, "#{t('.company_name')}", class: "right inline"
          .small-7.columns.large-9
            = f.text_field :company_name, placeholder: "#{t('.company_name_p')}"
            = render 'shared/er_message', model: @profile, attribute: :company_name
        .row
          .small-5.columns.large-3
            = f.label :description, "#{t('.about')}", class: "right inline"
          .small-7.columns.large-9
            = f.text_area :description, rows: 4, placeholder: "#{t('.about_p')}"
            = render 'shared/er_message', model: @profile, attribute: :description
        .row
          .small-5.columns.large-3
            = f.label :owner_name, "#{t('.owner_name')}", class: "right inline"
          .small-7.columns.large-9
            = f.text_field :owner_name, rows: 8, placeholder: "#{t('.owner_name_p')}"
            = render 'shared/er_message', model: @profile, attribute: :owner_name

      fieldset.profile
        legend = t('.contacts')
        .row
          .small-5.columns.large-3
            = f.label :phone_number, "#{t('.phone')}", class: "right inline"
          .small-7.columns.large-9
            = f.text_field :phone_number, placeholder: "+66 86-674-1343"
            = render 'shared/er_message', model: @profile, attribute: :phone_number
        .row
          .small-5.columns.large-3
            = f.label :email, "#{t('.email')}", class: "right inline"
          .small-7.columns.large-9
            = f.email_field :email, placeholder: "info@mandrigal.com"
            = render 'shared/er_message', model: @profile, attribute: :email
        .row
          .small-5.columns.large-3
            = f.label :website, "#{t('.website')}", class: "right inline"
          .small-7.columns.large-9
            = f.url_field :website, placeholder: "http://mandrigal.com"
            = render 'shared/er_message', model: @profile, attribute: :website
        .row
          .small-5.columns.large-3
            = f.label :twitter, "twitter.com/", class: "right inline"
          .small-7.columns.large-9
            = f.text_field :twitter, placeholder: "mandrigal"
            = render 'shared/er_message', model: @profile, attribute: :twitter
        .row
          .small-5.columns.large-3
            = f.label :facebook, "facebook.com/", class: "right inline"
          .small-7.columns.large-9
            = f.text_field :facebook, placeholder: "mandrigal"
            = render 'shared/er_message', model: @profile, attribute: :facebook


      .small-12.columns
        = f.submit "#{t('.update_button')}", class: "button"

app/views/profiles/edit.html.slim
/h1 Editing profile
= link_to 'Show', @profile

/.alert-box data-alert=""
/  | This information will be showed to everybody
/  a.close href="#" &times;
== render 'form'

app/views/profiles/index.html.slim
h1 Listing profiles

table
  tr
    th
    th
    th

  - @profiles.each do |profile|
    tr
      td = profile.company_name
    tr
      td = link_to 'Show', profile

app/views/profiles/new.html.slim
h1 New profile

== render 'form'

= link_to 'Back', profiles_path

app/views/profiles/show.html.slim
p= @profile.company_name
p= @profile.to_param
p= @profile.company_name.to_slug.transliterate(:russian).normalize.to_s
p= @profile.description
p= @profile.owner_name
p= @profile.phone_number
p= link_to @profile.website, @profile.website

ul.inline-list
  - if @profile.twitter?
    li
      = link_to @profile.twitter, "http://twitter.com/#{@profile.twitter}", class: "fc-webicon twitter"
  - if @profile.facebook?
    li
      = link_to @profile.facebook, "http://facebook.com/#{@profile.facebook}", class: "fc-webicon facebook"

- if current_user
  - if current_user.id == @profile.user_id
    = link_to "Edit", edit_profile_path