config/routes.rb
Rent::Application.routes.draw do

  scope '(:locale)' do
    root "houses#index"

    resources :ads
    devise_for :users
    resources :houses
    resources :profiles
    post 'lang_change', to: 'application#lang_change'
    get "/profile", to: 'profiles#show_profile'
    
  end

  

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    case cookies[:language]
    when "ru"
      I18n.locale = "ru"
    when "en"
      I18n.locale = "en"
    else
      I18n.locale = "ru"
    end

    @houses = House.all
    
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render action: 'show', status: :created, location: @house }
      else
        format.html { render action: 'new' }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:title, :description, :price)
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.slim
.row
  .large-12
    = form_for(@house) do |f|
      - if @house.errors.any?
        /#error_explanation
        .alert-box
          = pluralize(@house.errors.count, "error") 
          |  prohibited this house from being saved:
    
      fieldset.profile
        legend Main info about Realty
        .row
          .small-3.columns
            = f.label :title, "title", class: "right inline"
          .small-9.columns
            = f.text_field :title, placeholder: "a better place in the world... )))", required: true
            = render 'shared/er_message', model: @house, attribute: :title
        .row
          .small-3.columns
            = f.label :description, "description", class: "right inline"
          .small-9.columns
            = f.text_area :description, rows: 8, placeholder: "Describe the object", required: true
            = render 'shared/er_message', model: @house, attribute: :description
      fieldset.profile
        legend Price information
        .row
          .small-3.columns
            = f.label :price, "price per month", class: "right inline"
          .large-6.columns.pull-3
            .row.collapse
              .small-10.columns
                = f.text_field :price, required: true, title: "###,###"
                = render '/shared/er_message', model: @house, attribute: :price
              .small-2.columns
                span.postfix baht

      .small-12.columns
        = f.submit "create house", class: "button"

app/views/houses/edit.html.slim
h1 Editing house

== render 'form'

= link_to 'Show', @house
'|
= link_to 'Back', houses_path

app/views/houses/index.html.slim
h1 Listing houses

table
  tr
    th
    th
    th

  - @houses.each do |house|
    tr
      td= house.title
      td= house.price
      td= house.description
    tr
      td = link_to 'Show', house
      td = link_to 'Edit', edit_house_path(house)
      td = link_to 'Destroy', house, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New House', new_house_path

app/views/houses/new.html.slim
h1 New house

== render 'form'

= link_to 'Back', houses_path

app/views/houses/show.html.slim
p#notice = notice

p= @house.title
p= @house.price
p= @house.description

= link_to 'Edit', edit_house_path(@house)
'|
= link_to 'Back', houses_path